env:
  SECRET_CODECOV_TOKEN: "ZJoKq7+gD0BKAkXuHUEodQYl492UA38uoOMs336yjV8yas4Zmk4I2LPDq9tc4Rf86xM8eDF5wCnYuWAz+HMHQRDVh3TNc6yeA47/XWBuvcwT3pPtACKVrPd4wsoHQWBdbu4K7ZirGyuOscdQuVfBNUAoHH6dpcZw6ycHqHP6T8kgi1wb04lnCon23RnpZjEmL+o2rTh150db5nW8aOCJmHgZbIlQD8MCeShGhn3hBSxgVmVKwentxIfKetdJRtxfLTirgY7geoON5NEJBGbRUHpAiB+H66XcbeeJBfqE39gRc9dnjw4ZXKXyeLLNdVxnIYmmDF/XoyEV8uO9bwJLAQ==;U2FsdGVkX1+fLOI1HLKI6tX4Owg4Z035yq6HUZVgjbR9LFZwMqkuxamG8j1ju97bx6q1cieWOpepTtScT1rGcQ=="

steps:
  - label: "Julia v1 -- CUDA"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          dirs:
            - src
            - ext
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 30

  - label: "Julia LTS -- CUDA"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10" # "lts" isn't valid
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          dirs:
            - src
            - ext
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 30
