name: "Format Check"

on:
  push:
    branches:
      - 'main'
      - 'master'
    tags: '*'
  pull_request:

jobs:
  format-check:
    name: "Format Check"
    uses: "QuantumKitHub/.github/.github/workflows/formatcheck.yml@main"
    with:
      juliaformatter-version: "2"
